// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNTeM6-blwsF6dBw-2TWxSMRIlE-K2xn4',
    appId: '1:429768423431:web:1443ecbeace75acc7252a2',
    messagingSenderId: '429768423431',
    projectId: 'stock-market-app-bf2b4',
    authDomain: 'stock-market-app-bf2b4.firebaseapp.com',
    storageBucket: 'stock-market-app-bf2b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9atSkTduE-_QLSIVFNUnvkaqKUT01i9Y',
    appId: '1:429768423431:android:d62d5a2560f599957252a2',
    messagingSenderId: '429768423431',
    projectId: 'stock-market-app-bf2b4',
    storageBucket: 'stock-market-app-bf2b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvXabxT-PkNNbQvJd9suNXKLPgNhIaQv4',
    appId: '1:429768423431:ios:20921493c0f284737252a2',
    messagingSenderId: '429768423431',
    projectId: 'stock-market-app-bf2b4',
    storageBucket: 'stock-market-app-bf2b4.appspot.com',
    iosBundleId: 'com.example.stockMarketTradingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvXabxT-PkNNbQvJd9suNXKLPgNhIaQv4',
    appId: '1:429768423431:ios:6f21920bc05510ad7252a2',
    messagingSenderId: '429768423431',
    projectId: 'stock-market-app-bf2b4',
    storageBucket: 'stock-market-app-bf2b4.appspot.com',
    iosBundleId: 'com.example.stockMarketTradingApp.RunnerTests',
  );
}
